os: windows
language: csharp
mono: none
install:
  - choco install nuget.commandline
  - powershell -NoProfile -ExecutionPolicy Bypass ./GetDependencies.ps1
script:
  - powershell -NoProfile -ExecutionPolicy Bypass ./build.ps1
