os: windows
language: csharp
mono: none
install:
  - choco install nuget.commandline
  - powershell -NoProfile -ExecutionPolicy Bypass ./GetDependencies.ps1
script:
  - powershell -NoProfile -ExecutionPolicy Bypass ./build.ps1
deploy:
  provider: releases
  api_key:
    secure: UQHwFSD1ITpK73MAfszFDmJ0J7rft40ulqJIo/6GP0Xo8cXYSIhnk2NqalI/e9jbr6DbnOnqVXoIGTvg7PsKtAZ1R22ixpFKWrFGY5hoUUluQfpydLBFgtVGc8wkqi7h33/BxfC1FS5u2ObKahn50aNsR0HfkmnLnSJcAT20OT02m7uDxiRDAu4UDY7yZu3jsnwwBYSJ1QW2pq8+lq+mdUmZBhoPbKaLKtg79Al+KRTzd95k6yGZRGM1xoHxNVhdIEYrhEkmVtZtK1cdg7zsnjbo6BvDcrsgGT1qHZ1iONtXwCqT7a1ctZ8AV3WHYmdEV8rpwHugcUUMshoYvfDBj3tXHmqGhvcHuxi4I03g8D5e0+Tfi6I1m4kw9wOYhOqL4aU2khI+6XEFgaVdmotnE9hf4diEsbADyoCqK4/DRpwt9xmTLzVqEr9Ss7TE8wEg6zPfnkPBdwnrmWIvqB02dAJq5KEDblP0ZH4MyGVmZLxX/Gr/r5vXzyQLZ5vTuEcCsx2PLj3iZ4AmIpxLDtwDE+YtnVvwp9fdicKwcO4yjY7mkQ+3sIt1JpK94UBTTKvurU5KNSwxalHrIXPWw4ZSYJFWLcrx1HC3CoiDYAxj72o4ga3IR4atWhrj0aNPH2i4+i2BUCvKAuqvhRr9DbzJ5OyhzkT7JtJ2KThDnwkBwzg=
  skip_cleanup: true
  draft: true
  file_glob: true
  file: build/*
  on:
    repo: krokofant/NodeEnv
